import Context from 'docs/components/Context';
import globalStyle from '../global.css';
import GrowthStyle from '@growth-ui/react/growth.css';
import Head from 'next/head';
import NProgress from 'nprogress';
import React, { useState } from 'react';
import Router from 'next/router';
import theme from '../theme';
import { AppProps } from 'next/dist/shared/lib/router/router';
import 'nprogress/nprogress.css';

Router.events.on('routeChangeStart', () => {
  NProgress.start();
});
Router.events.on('routeChangeComplete', () => NProgress.done());
Router.events.on('routeChangeError', () => NProgress.done());

function App({ Component, pageProps }: AppProps) {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <>
      <Head>
        <title>Growth UI React</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/images/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/images/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/images/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/images/favicon-16x16.png"
        />
      </Head>
      <Context.Provider
        value={{
          darkMode,
          setDarkMode,
        }}
      >
        <GrowthStyle
          darkMode={darkMode}
          globalStyle={globalStyle}
          theme={theme}
        >
          <Component {...pageProps} />
        </GrowthStyle>
      </Context.Provider>
    </>
  );
}

export default App;
