// ======================================================
// Alignments
// ======================================================

export type FLOATS = 'left' | 'right';
export type TEXTALIGNMENTS = 'left' | 'center' | 'right' | 'justified';
export type VERTICALALIGNMENTS = 'baseline' | 'top' | 'middle' | 'bottom' | 'stretch';
export type HORIZONTALALIGNMENTS =
  | 'left'
  | 'center'
  | 'right'
  | 'space-between'
  | 'space-around'
  | 'space-evenly'
  | 'stretch';
export type POSITIONS =
  | 'top center'
  | 'top left'
  | 'top right'
  | 'bottom center'
  | 'bottom left'
  | 'bottom right'
  | 'right center'
  | 'left center';

// ======================================================
// Styling
// ======================================================
export type COLORS =
  | 'primary'
  | 'secondary'
  | 'black'
  | 'white'
  | 'gray-50'
  | 'gray-100'
  | 'gray-200'
  | 'gray-300'
  | 'gray-400'
  | 'gray-500'
  | 'gray-600'
  | 'gray-700'
  | 'gray-800'
  | 'gray-900'
  | 'red-50'
  | 'red-100'
  | 'red-200'
  | 'red-300'
  | 'red-400'
  | 'red-500'
  | 'red-600'
  | 'red-700'
  | 'red-800'
  | 'red-900'
  | 'blue-50'
  | 'blue-100'
  | 'blue-200'
  | 'blue-300'
  | 'blue-400'
  | 'blue-500'
  | 'blue-600'
  | 'blue-700'
  | 'blue-800'
  | 'blue-900'
  | 'green-50'
  | 'green-100'
  | 'green-200'
  | 'green-300'
  | 'green-400'
  | 'green-500'
  | 'green-600'
  | 'green-700'
  | 'green-800'
  | 'green-900'
  | 'pink-50'
  | 'pink-100'
  | 'pink-200'
  | 'pink-300'
  | 'pink-400'
  | 'pink-500'
  | 'pink-600'
  | 'pink-700'
  | 'pink-800'
  | 'pink-900'
  | 'indigo-50'
  | 'indigo-100'
  | 'indigo-200'
  | 'indigo-300'
  | 'indigo-400'
  | 'indigo-500'
  | 'indigo-600'
  | 'indigo-700'
  | 'indigo-800'
  | 'indigo-900'
  | 'yellow-50'
  | 'yellow-100'
  | 'yellow-200'
  | 'yellow-300'
  | 'yellow-400'
  | 'yellow-500'
  | 'yellow-600'
  | 'yellow-700'
  | 'yellow-800'
  | 'yellow-900'
  | 'purple-50'
  | 'purple-100'
  | 'purple-200'
  | 'purple-300'
  | 'purple-400'
  | 'purple-500'
  | 'purple-600'
  | 'purple-700'
  | 'purple-800'
  | 'purple-900';
export type SIZES = 'mini' | 'tiny' | 'small' | 'medium' | 'large' | 'big' | 'huge' | 'massive';

export type FONTSIZES =
  | '2xs'
  | 'xs'
  | 'sm'
  | 'base'
  | 'lg'
  | 'xl'
  | '2xl'
  | '3xl'
  | '4xl'
  | '5xl'
  | '6xl'
  | '7xl'
  | '8xl'
  | '9xl';

export type LINEHEIGHTS =
  | 'leading-3'
  | 'leading-4'
  | 'leading-5'
  | 'leading-6'
  | 'leading-7'
  | 'leading-8'
  | 'leading-9'
  | 'leading-10'
  | 'leading-none'
  | 'leading-tight'
  | 'leading-snug'
  | 'leading-normal'
  | 'leading-relaxed'
  | 'leading-loose';

// ======================================================
// Widths
// ======================================================
export type WIDTHS = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16;

// ======================================================
// Visibility
// ======================================================
export type ONLY = 'minimobile' | 'mobile' | 'tablet' | 'laptop' | 'computer' | 'widescreen';

// ======================================================
// Icon Names
// ======================================================
export type GrowthICONS =
  | 'activity'
  | 'add'
  | 'airplane'
  | 'amex-c'
  | 'analytics'
  | 'angle double left'
  | 'angle double right'
  | 'apache'
  | 'apple'
  | 'applepay-c'
  | 'archive'
  | 'arrow dropdown'
  | 'arrow right circle fill'
  | 'attach'
  | 'aws'
  | 'bank'
  | 'barchart'
  | 'bill'
  | 'bold'
  | 'bookmark'
  | 'browser'
  | 'camera'
  | 'cart'
  | 'category'
  | 'chat help'
  | 'check'
  | 'chevron down'
  | 'chevron left'
  | 'chevron right'
  | 'chevron up'
  | 'close'
  | 'codepen'
  | 'code slash'
  | 'comment'
  | 'cookie'
  | 'confirmation number'
  | 'cpu'
  | 'dashboard'
  | 'dashboard2'
  | 'dashboard3'
  | 'database'
  | 'database search'
  | 'democrat'
  | 'discover-c'
  | 'documents'
  | 'donate'
  | 'doordash'
  | 'dots horizontal rounded'
  | 'download'
  | 'drafts'
  | 'edit'
  | 'email'
  | 'email outline'
  | 'excelfile'
  | 'facebook'
  | 'file copy'
  | 'file copy outline'
  | 'file outline'
  | 'filepdf'
  | 'folder outline'
  | 'github'
  | 'global'
  | 'heart'
  | 'home'
  | 'image'
  | 'inbox'
  | 'instagram'
  | 'install'
  | 'italic'
  | 'key'
  | 'label important'
  | 'language'
  | 'link'
  | 'list ol'
  | 'list ul'
  | 'location'
  | 'lock'
  | 'log'
  | 'logout outline'
  | 'mailbox'
  | 'mail send'
  | 'mastercard-c'
  | 'memory'
  | 'memory2'
  | 'menu'
  | 'message'
  | 'newspaper'
  | 'nextjs'
  | 'nginx'
  | 'nodejs'
  | 'notification'
  | 'notifications'
  | 'notification active'
  | 'npm'
  | 'package'
  | 'paperclip'
  | 'partly sunny'
  | 'paypal-c'
  | 'people'
  | 'php'
  | 'pie chart'
  | 'play'
  | 'play skip back'
  | 'play skip forward'
  | 'price tag'
  | 'purchase tag'
  | 'puzzle'
  | 'python'
  | 'question'
  | 'react logo'
  | 'refresh outline'
  | 'republican'
  | 'rocket'
  | 's3'
  | 'school'
  | 'search'
  | 'search menu'
  | 'search outline'
  | 'security'
  | 'send'
  | 'settings'
  | 'share'
  | 'ship'
  | 'shipping'
  | 'shop'
  | 'shopping bag'
  | 'slack'
  | 'speaker phone'
  | 'star'
  | 'star fill'
  | 'star half'
  | 'sun'
  | 'support agent'
  | 'telescope'
  | 'terminal'
  | 'thumbs down'
  | 'thumbs up'
  | 'tool outline'
  | 'trash'
  | 'triangle down'
  | 'triangle up'
  | 'twitter'
  | 'underline'
  | 'user'
  | 'video security'
  | 'visa-c'
  | 'warning'
  | 'yarn'
  | 'youtube';
export type DATE_MASK =
  | 'mm/dd/yyyy'
  | 'mm-dd-yyyy'
  | 'mm.dd.yyyy'
  | 'mm/yyyy'
  | 'mm-yyyy'
  | 'mm.yyyy'
  | 'mm/yy'
  | 'mm-yy'
  | 'mm.yy'
  | 'yyyy/mm/dd'
  | 'yyyy-mm-dd'
  | 'yyyy.mm.dd'
  | 'yyyy/mm'
  | 'yyyy-mm'
  | 'yyyy.mm'
  | 'yy/mm'
  | 'yy-mm'
  | 'yy.mm'
  | 'dd.mm.yyyy'
  | 'dd/mm/yyyy'
  | 'dd-mm-yyyy'
  | 'mm/dd'
  | 'mm-dd'
  | 'mm.dd'
  | 'dd.mm'
  | 'dd-mm'
  | 'dd/mm';

export type Country =
  | 'Andorra'
  | 'United Arab Emirates'
  | 'Afghanistan'
  | 'Antigua and Barbuda'
  | 'Anguilla'
  | 'Albania'
  | 'Armenia'
  | 'Angola'
  | 'Antarctica'
  | 'Argentina'
  | 'American Samoa'
  | 'Austria'
  | 'Australia'
  | 'Aruba'
  | 'Åland Islands'
  | 'Azerbaijan'
  | 'Bosnia and Herzegovina'
  | 'Barbados'
  | 'Bangladesh'
  | 'Belgium'
  | 'Burkina Faso'
  | 'Bulgaria'
  | 'Bahrain'
  | 'Burundi'
  | 'Benin'
  | 'Saint Barthélemy'
  | 'Bermuda'
  | 'Brunei Darussalam'
  | 'Bolivia'
  | 'Bonaire, Sint Eustatius and Saba'
  | 'Brazil'
  | 'Bahamas'
  | 'Bhutan'
  | 'Bouvet Island'
  | 'Botswana'
  | 'Belarus'
  | 'Belize'
  | 'Canada'
  | 'Cocos (Keeling) Islands'
  | 'Congo Kinshasa'
  | 'Central African Republic'
  | 'Congo Brazzaville'
  | 'Switzerland'
  | "Côte D'Ivoire"
  | 'Cook Islands'
  | 'Chile'
  | 'Cameroon'
  | 'China'
  | 'Colombia'
  | 'Costa Rica'
  | 'Cuba'
  | 'Cape Verde'
  | 'Curaçao'
  | 'Christmas Island'
  | 'Cyprus'
  | 'Czech Republic'
  | 'Germany'
  | 'Djibouti'
  | 'Denmark'
  | 'Dominica'
  | 'Dominican Republic'
  | 'Algeria'
  | 'Ecuador'
  | 'Estonia'
  | 'Egypt'
  | 'Western Sahara'
  | 'Eritrea'
  | 'Spain'
  | 'Ethiopia'
  | 'Finland'
  | 'Fiji'
  | 'Falkland Islands (Malvinas)'
  | 'Micronesia'
  | 'Faroe Islands'
  | 'France'
  | 'Gabon'
  | 'United Kingdom'
  | 'Grenada'
  | 'Georgia'
  | 'French Guiana'
  | 'Guernsey'
  | 'Ghana'
  | 'Gibraltar'
  | 'Greenland'
  | 'Gambia'
  | 'Guinea'
  | 'Guadeloupe'
  | 'Equatorial Guinea'
  | 'Greece'
  | 'South Georgia'
  | 'Guatemala'
  | 'Guam'
  | 'Guinea-Bissau'
  | 'Guyana'
  | 'Hong Kong'
  | 'Heard Island and Mcdonald Islands'
  | 'Honduras'
  | 'Croatia'
  | 'Haiti'
  | 'Hungary'
  | 'Indonesia'
  | 'Ireland'
  | 'Israel'
  | 'Isle of Man'
  | 'India'
  | 'British Indian Ocean Territory'
  | 'Iraq'
  | 'Iran'
  | 'Iceland'
  | 'Italy'
  | 'Jersey'
  | 'Jamaica'
  | 'Jordan'
  | 'Japan'
  | 'Kenya'
  | 'Kyrgyzstan'
  | 'Cambodia'
  | 'Kiribati'
  | 'Comoros'
  | 'Saint Kitts and Nevis'
  | 'North Korea'
  | 'South Korea'
  | 'Kuwait'
  | 'Cayman Islands'
  | 'Kazakhstan'
  | "Lao People's Democratic Republic"
  | 'Lebanon'
  | 'Saint Lucia'
  | 'Liechtenstein'
  | 'Sri Lanka'
  | 'Liberia'
  | 'Lesotho'
  | 'Lithuania'
  | 'Luxembourg'
  | 'Latvia'
  | 'Libya'
  | 'Morocco'
  | 'Monaco'
  | 'Moldova'
  | 'Montenegro'
  | 'Saint Martin (French Part)'
  | 'Madagascar'
  | 'Marshall Islands'
  | 'Macedonia'
  | 'Mali'
  | 'Myanmar'
  | 'Mongolia'
  | 'Macao'
  | 'Northern Mariana Islands'
  | 'Martinique'
  | 'Mauritania'
  | 'Montserrat'
  | 'Malta'
  | 'Mauritius'
  | 'Maldives'
  | 'Malawi'
  | 'Mexico'
  | 'Malaysia'
  | 'Mozambique'
  | 'Namibia'
  | 'New Caledonia'
  | 'Niger'
  | 'Norfolk Island'
  | 'Nigeria'
  | 'Nicaragua'
  | 'Netherlands'
  | 'Norway'
  | 'Nepal'
  | 'Nauru'
  | 'Niue'
  | 'New Zealand'
  | 'Oman'
  | 'Panama'
  | 'Peru'
  | 'French Polynesia'
  | 'Papua New Guinea'
  | 'Philippines'
  | 'Pakistan'
  | 'Poland'
  | 'Saint Pierre and Miquelon'
  | 'Pitcairn'
  | 'Puerto Rico'
  | 'Palestinian Territory'
  | 'Portugal'
  | 'Palau'
  | 'Paraguay'
  | 'Qatar'
  | 'Réunion'
  | 'Romania'
  | 'Serbia'
  | 'Russia'
  | 'Rwanda'
  | 'Saudi Arabia'
  | 'Solomon Islands'
  | 'Seychelles'
  | 'Sudan'
  | 'Sweden'
  | 'Singapore'
  | 'Saint Helena, Ascension and Tristan Da Cunha'
  | 'Slovenia'
  | 'Svalbard and Jan Mayen'
  | 'Slovakia'
  | 'Sierra Leone'
  | 'San Marino'
  | 'Senegal'
  | 'Somalia'
  | 'Suriname'
  | 'South Sudan'
  | 'Sao Tome and Principe'
  | 'El Salvador'
  | 'Sint Maarten (Dutch Part)'
  | 'Syrian Arab Republic'
  | 'Swaziland'
  | 'Turks and Caicos Islands'
  | 'Chad'
  | 'French Southern Territories'
  | 'Togo'
  | 'Thailand'
  | 'Tajikistan'
  | 'Tokelau'
  | 'Timor-Leste'
  | 'Turkmenistan'
  | 'Tunisia'
  | 'Tonga'
  | 'Turkey'
  | 'Trinidad and Tobago'
  | 'Tuvalu'
  | 'Taiwan'
  | 'Tanzania'
  | 'Ukraine'
  | 'Uganda'
  | 'United States Minor Outlying Islands'
  | 'United States'
  | 'Uruguay'
  | 'Uzbekistan'
  | 'Vatican City'
  | 'Saint Vincent and The Grenadines'
  | 'Venezuela'
  | 'Virgin Islands, British'
  | 'Virgin Islands, U.S.'
  | 'Viet Nam'
  | 'Vanuatu'
  | 'Wallis and Futuna'
  | 'Samoa'
  | 'Yemen'
  | 'Mayotte'
  | 'South Africa'
  | 'Zambia'
  | 'Zimbabwe';
